Fixed so that the version number in ovdisis.m4 is updated automatically amongst other things.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1784,6 +1784,53 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+echo $ac_n "checking for pthread_create in -lpthread""... $ac_c" 1>&6
+echo "configure:1789: checking for pthread_create in -lpthread" >&5
+ac_lib_var=`echo pthread'_'pthread_create | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lpthread  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 1797 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char pthread_create();
+
+int main() {
+pthread_create()
+; return 0; }
+EOF
+if { (eval echo configure:1808: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_lib=HAVE_LIB`echo pthread | sed -e 's/[^a-zA-Z0-9_]/_/g' \
+    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_lib 1
+EOF
+
+  LIBS="-lpthread $LIBS"
+
+else
+  echo "$ac_t""no" 1>&6
+fi
+
 
 if test x$with_ofbis = xyes ; then
   { echo "configure: error: 
@@ -1834,7 +1881,7 @@ fi
   # Extract the first word of "ofbis-config", so it can be a program name with args.
 set dummy ofbis-config; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1838: checking for $ac_word" >&5
+echo "configure:1885: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_OFBIS_CONFIG'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1865,7 +1912,7 @@ fi
 
   min_ofbis_version=0.0.6
   echo $ac_n "checking for oFBis - version >= $min_ofbis_version""... $ac_c" 1>&6
-echo "configure:1869: checking for oFBis - version >= $min_ofbis_version" >&5
+echo "configure:1916: checking for oFBis - version >= $min_ofbis_version" >&5
   no_ofbis=""
   if test "$OFBIS_CONFIG" = "no" ; then
     no_ofbis=yes
@@ -2048,7 +2095,7 @@ done
 ac_given_srcdir=$srcdir
 ac_given_INSTALL="$INSTALL"
 
-trap 'rm -fr `echo "fntread/Makefile src/Makefile vdi_dump/Makefile Makefile ovdisis-config config.h" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "fntread/Makefile src/Makefile vdi_dump/Makefile Makefile ovdisis.m4 ovdisis-config config.h" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -2147,7 +2194,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"fntread/Makefile src/Makefile vdi_dump/Makefile Makefile ovdisis-config"}
+CONFIG_FILES=\${CONFIG_FILES-"fntread/Makefile src/Makefile vdi_dump/Makefile Makefile ovdisis.m4 ovdisis-config"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
